/*
 * generated by Xtext 2.25.0
 */
package greenhouse.ui.tests;

import com.google.inject.Injector;
import greenhouse.ui.internal.GreenhouseActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class GreenHouseUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return GreenhouseActivator.getInstance().getInjector("greenhouse.GreenHouse");
	}

}
