/*
 * generated by Xtext 2.25.0
 */
package greenhouse.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class GreenHouseUiModule extends AbstractGreenHouseUiModule {

	public GreenHouseUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
