/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dsl.greenhouse.GreenhouseFactory
 * @model kind="package"
 * @generated
 */
public interface GreenhousePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "greenhouse";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Greenhouse.dsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "greenhouse";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  GreenhousePackage eINSTANCE = dsl.greenhouse.impl.GreenhousePackageImpl.init();

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ModelImpl <em>Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ModelImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getModel()
   * @generated
   */
  int MODEL = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__NAME = 0;

  /**
   * The feature id for the '<em><b>Hardware Setup</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__HARDWARE_SETUP = 1;

  /**
   * The feature id for the '<em><b>Greenhouses</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL__GREENHOUSES = 2;

  /**
   * The number of structural features of the '<em>Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODEL_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.HardwareSetupImpl <em>Hardware Setup</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.HardwareSetupImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardwareSetup()
   * @generated
   */
  int HARDWARE_SETUP = 1;

  /**
   * The number of structural features of the '<em>Hardware Setup</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE_SETUP_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.HardwareImpl <em>Hardware</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.HardwareImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardware()
   * @generated
   */
  int HARDWARE = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE__NAME = 0;

  /**
   * The feature id for the '<em><b>Topic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE__TOPIC = 1;

  /**
   * The number of structural features of the '<em>Hardware</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HARDWARE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingActuatorImpl <em>Setting Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingActuatorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingActuator()
   * @generated
   */
  int SETTING_ACTUATOR = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR__NAME = HARDWARE__NAME;

  /**
   * The feature id for the '<em><b>Topic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR__TOPIC = HARDWARE__TOPIC;

  /**
   * The feature id for the '<em><b>Setting Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR__SETTING_ACTION = HARDWARE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Setting Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTUATOR_FEATURE_COUNT = HARDWARE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingSensorImpl <em>Setting Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingSensorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingSensor()
   * @generated
   */
  int SETTING_SENSOR = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR__NAME = HARDWARE__NAME;

  /**
   * The feature id for the '<em><b>Topic</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR__TOPIC = HARDWARE__TOPIC;

  /**
   * The number of structural features of the '<em>Setting Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_SENSOR_FEATURE_COUNT = HARDWARE_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.TopicImpl <em>Topic</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.TopicImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getTopic()
   * @generated
   */
  int TOPIC = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC__NAME = 0;

  /**
   * The number of structural features of the '<em>Topic</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TOPIC_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingActionImpl <em>Setting Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingActionImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingAction()
   * @generated
   */
  int SETTING_ACTION = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Setting Value</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTION__SETTING_VALUE = 1;

  /**
   * The number of structural features of the '<em>Setting Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingValueImpl <em>Setting Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingValueImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingValue()
   * @generated
   */
  int SETTING_VALUE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Setting Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseImpl <em>Greenhouse</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouse()
   * @generated
   */
  int GREENHOUSE = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE__NAME = 0;

  /**
   * The feature id for the '<em><b>Row</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE__ROW = 1;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE__ELEMENTS = 2;

  /**
   * The number of structural features of the '<em>Greenhouse</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowImpl <em>Row</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRow()
   * @generated
   */
  int ROW = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__NAME = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW__ELEMENTS = 1;

  /**
   * The number of structural features of the '<em>Row</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseElementImpl <em>Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseElementImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseElement()
   * @generated
   */
  int GREENHOUSE_ELEMENT = 10;

  /**
   * The number of structural features of the '<em>Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowElementImpl <em>Row Element</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowElementImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowElement()
   * @generated
   */
  int ROW_ELEMENT = 11;

  /**
   * The number of structural features of the '<em>Row Element</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ELEMENT_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseActuatorImpl <em>Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseActuatorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseActuator()
   * @generated
   */
  int GREENHOUSE_ACTUATOR = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__NAME = GREENHOUSE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR__ACTION = GREENHOUSE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_ACTUATOR_FEATURE_COUNT = GREENHOUSE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowActuatorImpl <em>Row Actuator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowActuatorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowActuator()
   * @generated
   */
  int ROW_ACTUATOR = 13;

  /**
   * The feature id for the '<em><b>Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__TYPE = ROW_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__NAME = ROW_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Action</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR__ACTION = ROW_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Row Actuator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_ACTUATOR_FEATURE_COUNT = ROW_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseSensorImpl <em>Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseSensorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseSensor()
   * @generated
   */
  int GREENHOUSE_SENSOR = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__NAME = GREENHOUSE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__VARIABLE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR__STATES = GREENHOUSE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_SENSOR_FEATURE_COUNT = GREENHOUSE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowSensorImpl <em>Row Sensor</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowSensorImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowSensor()
   * @generated
   */
  int ROW_SENSOR = 15;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__NAME = ROW_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__VARIABLE = ROW_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR__STATES = ROW_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Row Sensor</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_SENSOR_FEATURE_COUNT = ROW_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.StateImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getState()
   * @generated
   */
  int STATE = 16;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 0;

  /**
   * The feature id for the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__VARIABLE = 1;

  /**
   * The feature id for the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__OP = 2;

  /**
   * The feature id for the '<em><b>Threshold</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__THRESHOLD = 3;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.VariableImpl <em>Variable</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.VariableImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getVariable()
   * @generated
   */
  int VARIABLE = 17;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE__NAME = 0;

  /**
   * The number of structural features of the '<em>Variable</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ActionImpl <em>Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ActionImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getAction()
   * @generated
   */
  int ACTION = 18;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__NAME = 0;

  /**
   * The feature id for the '<em><b>Trigger</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__TRIGGER = 1;

  /**
   * The feature id for the '<em><b>Condition</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__CONDITION = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION__VALUE = 3;

  /**
   * The number of structural features of the '<em>Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ACTION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.TriggerImpl <em>Trigger</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.TriggerImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getTrigger()
   * @generated
   */
  int TRIGGER = 19;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER__NAME = 0;

  /**
   * The number of structural features of the '<em>Trigger</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRIGGER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ConditionImpl <em>Condition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ConditionImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getCondition()
   * @generated
   */
  int CONDITION = 20;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION__NAME = 0;

  /**
   * The number of structural features of the '<em>Condition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDITION_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.ValueImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getValue()
   * @generated
   */
  int VALUE = 21;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__NAME = 0;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.RowRuleSetImpl <em>Row Rule Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.RowRuleSetImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowRuleSet()
   * @generated
   */
  int ROW_RULE_SET = 22;

  /**
   * The feature id for the '<em><b>Actuator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__ACTUATOR = ROW_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__ACTION = ROW_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__SENSOR = ROW_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET__STATE = ROW_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Row Rule Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROW_RULE_SET_FEATURE_COUNT = ROW_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.GreenhouseRuleSetImpl <em>Rule Set</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.GreenhouseRuleSetImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseRuleSet()
   * @generated
   */
  int GREENHOUSE_RULE_SET = 23;

  /**
   * The feature id for the '<em><b>Actuator</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__ACTUATOR = GREENHOUSE_ELEMENT_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Action</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__ACTION = GREENHOUSE_ELEMENT_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Sensor</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__SENSOR = GREENHOUSE_ELEMENT_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>State</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET__STATE = GREENHOUSE_ELEMENT_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Rule Set</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GREENHOUSE_RULE_SET_FEATURE_COUNT = GREENHOUSE_ELEMENT_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link dsl.greenhouse.impl.SettingImpl <em>Setting</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dsl.greenhouse.impl.SettingImpl
   * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSetting()
   * @generated
   */
  int SETTING = 24;

  /**
   * The feature id for the '<em><b>Hardware</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING__HARDWARE = HARDWARE_SETUP_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Setting</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SETTING_FEATURE_COUNT = HARDWARE_SETUP_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Model <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Model</em>'.
   * @see dsl.greenhouse.Model
   * @generated
   */
  EClass getModel();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Model#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Model#getName()
   * @see #getModel()
   * @generated
   */
  EAttribute getModel_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Model#getHardwareSetup <em>Hardware Setup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hardware Setup</em>'.
   * @see dsl.greenhouse.Model#getHardwareSetup()
   * @see #getModel()
   * @generated
   */
  EReference getModel_HardwareSetup();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Model#getGreenhouses <em>Greenhouses</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Greenhouses</em>'.
   * @see dsl.greenhouse.Model#getGreenhouses()
   * @see #getModel()
   * @generated
   */
  EReference getModel_Greenhouses();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.HardwareSetup <em>Hardware Setup</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hardware Setup</em>'.
   * @see dsl.greenhouse.HardwareSetup
   * @generated
   */
  EClass getHardwareSetup();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Hardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Hardware</em>'.
   * @see dsl.greenhouse.Hardware
   * @generated
   */
  EClass getHardware();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Hardware#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Hardware#getName()
   * @see #getHardware()
   * @generated
   */
  EAttribute getHardware_Name();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Hardware#getTopic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Topic</em>'.
   * @see dsl.greenhouse.Hardware#getTopic()
   * @see #getHardware()
   * @generated
   */
  EReference getHardware_Topic();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingActuator <em>Setting Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Actuator</em>'.
   * @see dsl.greenhouse.SettingActuator
   * @generated
   */
  EClass getSettingActuator();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.SettingActuator#getSettingAction <em>Setting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Setting Action</em>'.
   * @see dsl.greenhouse.SettingActuator#getSettingAction()
   * @see #getSettingActuator()
   * @generated
   */
  EReference getSettingActuator_SettingAction();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingSensor <em>Setting Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Sensor</em>'.
   * @see dsl.greenhouse.SettingSensor
   * @generated
   */
  EClass getSettingSensor();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Topic <em>Topic</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Topic</em>'.
   * @see dsl.greenhouse.Topic
   * @generated
   */
  EClass getTopic();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Topic#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Topic#getName()
   * @see #getTopic()
   * @generated
   */
  EAttribute getTopic_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingAction <em>Setting Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Action</em>'.
   * @see dsl.greenhouse.SettingAction
   * @generated
   */
  EClass getSettingAction();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.SettingAction#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.SettingAction#getName()
   * @see #getSettingAction()
   * @generated
   */
  EAttribute getSettingAction_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.SettingAction#getSettingValue <em>Setting Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Setting Value</em>'.
   * @see dsl.greenhouse.SettingAction#getSettingValue()
   * @see #getSettingAction()
   * @generated
   */
  EReference getSettingAction_SettingValue();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.SettingValue <em>Setting Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting Value</em>'.
   * @see dsl.greenhouse.SettingValue
   * @generated
   */
  EClass getSettingValue();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.SettingValue#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.SettingValue#getName()
   * @see #getSettingValue()
   * @generated
   */
  EAttribute getSettingValue_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Greenhouse <em>Greenhouse</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Greenhouse</em>'.
   * @see dsl.greenhouse.Greenhouse
   * @generated
   */
  EClass getGreenhouse();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Greenhouse#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Greenhouse#getName()
   * @see #getGreenhouse()
   * @generated
   */
  EAttribute getGreenhouse_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Greenhouse#getRow <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Row</em>'.
   * @see dsl.greenhouse.Greenhouse#getRow()
   * @see #getGreenhouse()
   * @generated
   */
  EReference getGreenhouse_Row();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Greenhouse#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see dsl.greenhouse.Greenhouse#getElements()
   * @see #getGreenhouse()
   * @generated
   */
  EReference getGreenhouse_Elements();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Row <em>Row</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row</em>'.
   * @see dsl.greenhouse.Row
   * @generated
   */
  EClass getRow();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Row#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Row#getName()
   * @see #getRow()
   * @generated
   */
  EAttribute getRow_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Row#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Elements</em>'.
   * @see dsl.greenhouse.Row#getElements()
   * @see #getRow()
   * @generated
   */
  EReference getRow_Elements();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseElement <em>Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Element</em>'.
   * @see dsl.greenhouse.GreenhouseElement
   * @generated
   */
  EClass getGreenhouseElement();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowElement <em>Row Element</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Element</em>'.
   * @see dsl.greenhouse.RowElement
   * @generated
   */
  EClass getRowElement();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Actuator</em>'.
   * @see dsl.greenhouse.GreenhouseActuator
   * @generated
   */
  EClass getGreenhouseActuator();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.GreenhouseActuator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getName()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EAttribute getGreenhouseActuator_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.GreenhouseActuator#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see dsl.greenhouse.GreenhouseActuator#getAction()
   * @see #getGreenhouseActuator()
   * @generated
   */
  EReference getGreenhouseActuator_Action();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowActuator <em>Row Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Actuator</em>'.
   * @see dsl.greenhouse.RowActuator
   * @generated
   */
  EClass getRowActuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowActuator#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Type</em>'.
   * @see dsl.greenhouse.RowActuator#getType()
   * @see #getRowActuator()
   * @generated
   */
  EReference getRowActuator_Type();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.RowActuator#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.RowActuator#getName()
   * @see #getRowActuator()
   * @generated
   */
  EAttribute getRowActuator_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.RowActuator#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Action</em>'.
   * @see dsl.greenhouse.RowActuator#getAction()
   * @see #getRowActuator()
   * @generated
   */
  EReference getRowActuator_Action();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Sensor</em>'.
   * @see dsl.greenhouse.GreenhouseSensor
   * @generated
   */
  EClass getGreenhouseSensor();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.GreenhouseSensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getName()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EAttribute getGreenhouseSensor_Name();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.GreenhouseSensor#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getVariable()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EReference getGreenhouseSensor_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.GreenhouseSensor#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see dsl.greenhouse.GreenhouseSensor#getStates()
   * @see #getGreenhouseSensor()
   * @generated
   */
  EReference getGreenhouseSensor_States();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowSensor <em>Row Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Sensor</em>'.
   * @see dsl.greenhouse.RowSensor
   * @generated
   */
  EClass getRowSensor();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.RowSensor#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.RowSensor#getName()
   * @see #getRowSensor()
   * @generated
   */
  EAttribute getRowSensor_Name();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.RowSensor#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Variable</em>'.
   * @see dsl.greenhouse.RowSensor#getVariable()
   * @see #getRowSensor()
   * @generated
   */
  EReference getRowSensor_Variable();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.RowSensor#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see dsl.greenhouse.RowSensor#getStates()
   * @see #getRowSensor()
   * @generated
   */
  EReference getRowSensor_States();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see dsl.greenhouse.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.State#getVariable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Variable</em>'.
   * @see dsl.greenhouse.State#getVariable()
   * @see #getState()
   * @generated
   */
  EReference getState_Variable();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.State#getOp <em>Op</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Op</em>'.
   * @see dsl.greenhouse.State#getOp()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Op();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.State#getThreshold <em>Threshold</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Threshold</em>'.
   * @see dsl.greenhouse.State#getThreshold()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Threshold();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Variable <em>Variable</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable</em>'.
   * @see dsl.greenhouse.Variable
   * @generated
   */
  EClass getVariable();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Variable#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Variable#getName()
   * @see #getVariable()
   * @generated
   */
  EAttribute getVariable_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Action <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Action</em>'.
   * @see dsl.greenhouse.Action
   * @generated
   */
  EClass getAction();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Action#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Action#getName()
   * @see #getAction()
   * @generated
   */
  EAttribute getAction_Name();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Action#getTrigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Trigger</em>'.
   * @see dsl.greenhouse.Action#getTrigger()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Trigger();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Action#getCondition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Condition</em>'.
   * @see dsl.greenhouse.Action#getCondition()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Condition();

  /**
   * Returns the meta object for the containment reference '{@link dsl.greenhouse.Action#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see dsl.greenhouse.Action#getValue()
   * @see #getAction()
   * @generated
   */
  EReference getAction_Value();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Trigger <em>Trigger</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trigger</em>'.
   * @see dsl.greenhouse.Trigger
   * @generated
   */
  EClass getTrigger();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Trigger#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Trigger#getName()
   * @see #getTrigger()
   * @generated
   */
  EAttribute getTrigger_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Condition <em>Condition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Condition</em>'.
   * @see dsl.greenhouse.Condition
   * @generated
   */
  EClass getCondition();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Condition#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Condition#getName()
   * @see #getCondition()
   * @generated
   */
  EAttribute getCondition_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see dsl.greenhouse.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the attribute '{@link dsl.greenhouse.Value#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dsl.greenhouse.Value#getName()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Name();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.RowRuleSet <em>Row Rule Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Row Rule Set</em>'.
   * @see dsl.greenhouse.RowRuleSet
   * @generated
   */
  EClass getRowRuleSet();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actuator</em>'.
   * @see dsl.greenhouse.RowRuleSet#getActuator()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_Actuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Action</em>'.
   * @see dsl.greenhouse.RowRuleSet#getAction()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_Action();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see dsl.greenhouse.RowRuleSet#getSensor()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_Sensor();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.RowRuleSet#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see dsl.greenhouse.RowRuleSet#getState()
   * @see #getRowRuleSet()
   * @generated
   */
  EReference getRowRuleSet_State();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.GreenhouseRuleSet <em>Rule Set</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rule Set</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet
   * @generated
   */
  EClass getGreenhouseRuleSet();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getActuator <em>Actuator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Actuator</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getActuator()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_Actuator();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Action</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getAction()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_Action();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getSensor <em>Sensor</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Sensor</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getSensor()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_Sensor();

  /**
   * Returns the meta object for the reference '{@link dsl.greenhouse.GreenhouseRuleSet#getState <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>State</em>'.
   * @see dsl.greenhouse.GreenhouseRuleSet#getState()
   * @see #getGreenhouseRuleSet()
   * @generated
   */
  EReference getGreenhouseRuleSet_State();

  /**
   * Returns the meta object for class '{@link dsl.greenhouse.Setting <em>Setting</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Setting</em>'.
   * @see dsl.greenhouse.Setting
   * @generated
   */
  EClass getSetting();

  /**
   * Returns the meta object for the containment reference list '{@link dsl.greenhouse.Setting#getHardware <em>Hardware</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Hardware</em>'.
   * @see dsl.greenhouse.Setting#getHardware()
   * @see #getSetting()
   * @generated
   */
  EReference getSetting_Hardware();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  GreenhouseFactory getGreenhouseFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ModelImpl <em>Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ModelImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getModel()
     * @generated
     */
    EClass MODEL = eINSTANCE.getModel();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MODEL__NAME = eINSTANCE.getModel_Name();

    /**
     * The meta object literal for the '<em><b>Hardware Setup</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__HARDWARE_SETUP = eINSTANCE.getModel_HardwareSetup();

    /**
     * The meta object literal for the '<em><b>Greenhouses</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODEL__GREENHOUSES = eINSTANCE.getModel_Greenhouses();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.HardwareSetupImpl <em>Hardware Setup</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.HardwareSetupImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardwareSetup()
     * @generated
     */
    EClass HARDWARE_SETUP = eINSTANCE.getHardwareSetup();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.HardwareImpl <em>Hardware</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.HardwareImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getHardware()
     * @generated
     */
    EClass HARDWARE = eINSTANCE.getHardware();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute HARDWARE__NAME = eINSTANCE.getHardware_Name();

    /**
     * The meta object literal for the '<em><b>Topic</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HARDWARE__TOPIC = eINSTANCE.getHardware_Topic();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingActuatorImpl <em>Setting Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingActuatorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingActuator()
     * @generated
     */
    EClass SETTING_ACTUATOR = eINSTANCE.getSettingActuator();

    /**
     * The meta object literal for the '<em><b>Setting Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING_ACTUATOR__SETTING_ACTION = eINSTANCE.getSettingActuator_SettingAction();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingSensorImpl <em>Setting Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingSensorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingSensor()
     * @generated
     */
    EClass SETTING_SENSOR = eINSTANCE.getSettingSensor();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.TopicImpl <em>Topic</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.TopicImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getTopic()
     * @generated
     */
    EClass TOPIC = eINSTANCE.getTopic();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TOPIC__NAME = eINSTANCE.getTopic_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingActionImpl <em>Setting Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingActionImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingAction()
     * @generated
     */
    EClass SETTING_ACTION = eINSTANCE.getSettingAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SETTING_ACTION__NAME = eINSTANCE.getSettingAction_Name();

    /**
     * The meta object literal for the '<em><b>Setting Value</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING_ACTION__SETTING_VALUE = eINSTANCE.getSettingAction_SettingValue();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingValueImpl <em>Setting Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingValueImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSettingValue()
     * @generated
     */
    EClass SETTING_VALUE = eINSTANCE.getSettingValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SETTING_VALUE__NAME = eINSTANCE.getSettingValue_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseImpl <em>Greenhouse</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouse()
     * @generated
     */
    EClass GREENHOUSE = eINSTANCE.getGreenhouse();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREENHOUSE__NAME = eINSTANCE.getGreenhouse_Name();

    /**
     * The meta object literal for the '<em><b>Row</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE__ROW = eINSTANCE.getGreenhouse_Row();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE__ELEMENTS = eINSTANCE.getGreenhouse_Elements();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowImpl <em>Row</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRow()
     * @generated
     */
    EClass ROW = eINSTANCE.getRow();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW__NAME = eINSTANCE.getRow_Name();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW__ELEMENTS = eINSTANCE.getRow_Elements();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseElementImpl <em>Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseElementImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseElement()
     * @generated
     */
    EClass GREENHOUSE_ELEMENT = eINSTANCE.getGreenhouseElement();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowElementImpl <em>Row Element</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowElementImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowElement()
     * @generated
     */
    EClass ROW_ELEMENT = eINSTANCE.getRowElement();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseActuatorImpl <em>Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseActuatorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseActuator()
     * @generated
     */
    EClass GREENHOUSE_ACTUATOR = eINSTANCE.getGreenhouseActuator();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREENHOUSE_ACTUATOR__NAME = eINSTANCE.getGreenhouseActuator_Name();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_ACTUATOR__ACTION = eINSTANCE.getGreenhouseActuator_Action();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowActuatorImpl <em>Row Actuator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowActuatorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowActuator()
     * @generated
     */
    EClass ROW_ACTUATOR = eINSTANCE.getRowActuator();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_ACTUATOR__TYPE = eINSTANCE.getRowActuator_Type();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_ACTUATOR__NAME = eINSTANCE.getRowActuator_Name();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_ACTUATOR__ACTION = eINSTANCE.getRowActuator_Action();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseSensorImpl <em>Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseSensorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseSensor()
     * @generated
     */
    EClass GREENHOUSE_SENSOR = eINSTANCE.getGreenhouseSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute GREENHOUSE_SENSOR__NAME = eINSTANCE.getGreenhouseSensor_Name();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_SENSOR__VARIABLE = eINSTANCE.getGreenhouseSensor_Variable();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_SENSOR__STATES = eINSTANCE.getGreenhouseSensor_States();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowSensorImpl <em>Row Sensor</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowSensorImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowSensor()
     * @generated
     */
    EClass ROW_SENSOR = eINSTANCE.getRowSensor();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROW_SENSOR__NAME = eINSTANCE.getRowSensor_Name();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SENSOR__VARIABLE = eINSTANCE.getRowSensor_Variable();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_SENSOR__STATES = eINSTANCE.getRowSensor_States();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.StateImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Variable</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__VARIABLE = eINSTANCE.getState_Variable();

    /**
     * The meta object literal for the '<em><b>Op</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__OP = eINSTANCE.getState_Op();

    /**
     * The meta object literal for the '<em><b>Threshold</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__THRESHOLD = eINSTANCE.getState_Threshold();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.VariableImpl <em>Variable</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.VariableImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getVariable()
     * @generated
     */
    EClass VARIABLE = eINSTANCE.getVariable();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE__NAME = eINSTANCE.getVariable_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ActionImpl <em>Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ActionImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getAction()
     * @generated
     */
    EClass ACTION = eINSTANCE.getAction();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ACTION__NAME = eINSTANCE.getAction_Name();

    /**
     * The meta object literal for the '<em><b>Trigger</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__TRIGGER = eINSTANCE.getAction_Trigger();

    /**
     * The meta object literal for the '<em><b>Condition</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__CONDITION = eINSTANCE.getAction_Condition();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ACTION__VALUE = eINSTANCE.getAction_Value();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.TriggerImpl <em>Trigger</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.TriggerImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getTrigger()
     * @generated
     */
    EClass TRIGGER = eINSTANCE.getTrigger();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRIGGER__NAME = eINSTANCE.getTrigger_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ConditionImpl <em>Condition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ConditionImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getCondition()
     * @generated
     */
    EClass CONDITION = eINSTANCE.getCondition();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONDITION__NAME = eINSTANCE.getCondition_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.ValueImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__NAME = eINSTANCE.getValue_Name();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.RowRuleSetImpl <em>Row Rule Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.RowRuleSetImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getRowRuleSet()
     * @generated
     */
    EClass ROW_RULE_SET = eINSTANCE.getRowRuleSet();

    /**
     * The meta object literal for the '<em><b>Actuator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__ACTUATOR = eINSTANCE.getRowRuleSet_Actuator();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__ACTION = eINSTANCE.getRowRuleSet_Action();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__SENSOR = eINSTANCE.getRowRuleSet_Sensor();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROW_RULE_SET__STATE = eINSTANCE.getRowRuleSet_State();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.GreenhouseRuleSetImpl <em>Rule Set</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.GreenhouseRuleSetImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getGreenhouseRuleSet()
     * @generated
     */
    EClass GREENHOUSE_RULE_SET = eINSTANCE.getGreenhouseRuleSet();

    /**
     * The meta object literal for the '<em><b>Actuator</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__ACTUATOR = eINSTANCE.getGreenhouseRuleSet_Actuator();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__ACTION = eINSTANCE.getGreenhouseRuleSet_Action();

    /**
     * The meta object literal for the '<em><b>Sensor</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__SENSOR = eINSTANCE.getGreenhouseRuleSet_Sensor();

    /**
     * The meta object literal for the '<em><b>State</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GREENHOUSE_RULE_SET__STATE = eINSTANCE.getGreenhouseRuleSet_State();

    /**
     * The meta object literal for the '{@link dsl.greenhouse.impl.SettingImpl <em>Setting</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dsl.greenhouse.impl.SettingImpl
     * @see dsl.greenhouse.impl.GreenhousePackageImpl#getSetting()
     * @generated
     */
    EClass SETTING = eINSTANCE.getSetting();

    /**
     * The meta object literal for the '<em><b>Hardware</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SETTING__HARDWARE = eINSTANCE.getSetting_Hardware();

  }

} //GreenhousePackage
