/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Setting</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dsl.greenhouse.Setting#getHardware <em>Hardware</em>}</li>
 * </ul>
 *
 * @see dsl.greenhouse.GreenhousePackage#getSetting()
 * @model
 * @generated
 */
public interface Setting extends HardwareSetup
{
  /**
   * Returns the value of the '<em><b>Hardware</b></em>' containment reference list.
   * The list contents are of type {@link dsl.greenhouse.Hardware}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Hardware</em>' containment reference list.
   * @see dsl.greenhouse.GreenhousePackage#getSetting_Hardware()
   * @model containment="true"
   * @generated
   */
  EList<Hardware> getHardware();

} // Setting
