/**
 * generated by Xtext 2.25.0
 */
package dsl.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class GreenhouseScopeProvider extends AbstractGreenhouseScopeProvider {
  @Override
  public IScope getScope(final EObject context, final EReference reference) {
    return this.scopeForEObject(context, reference);
  }
  
  protected IScope _scopeForEObject(final EObject context, final EReference reference) {
    return super.getScope(context.eContainer(), reference);
  }
  
  public IScope scopeForAction(final EObject context) {
    return null;
  }
  
  public IScope scopeForEObject(final EObject context, final EReference reference) {
    return _scopeForEObject(context, reference);
  }
}
