/**
 * generated by Xtext 2.25.0
 */
package dsl.greenhouse.impl;

import dsl.greenhouse.GreenhousePackage;
import dsl.greenhouse.HardwareSetup;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Hardware Setup</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class HardwareSetupImpl extends MinimalEObjectImpl.Container implements HardwareSetup
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected HardwareSetupImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GreenhousePackage.Literals.HARDWARE_SETUP;
  }

} //HardwareSetupImpl
